### ISSUE TITLE
quit and enter strange use of params and modifiers

### ISSUE THREAD

**Issue by gbalabasquer** [OasisDEX/oasis-cdp-manager#2]
The idea of `quit` and `enter` is to export and import a position from and to the manager respectively. It was mainly thought to be able to upgrade the manager in the future.

The original manager has a more complex authorization  to handle it due the possibility to send or import it to and from everywhere.
However in this code I can see both functions invoke to `isAllowed(src) isAllowed(usr)`.
In this case `isAllowed` just check the passed address is `msg.sender`, then the only way to pass the modifier is `src` and `usr` are the same.
Question is why we need 2 parameters, actually why we need a parameter at all. If what we want is that we can export and import from the msg.sender address (owner) to the cdp in the manager and viceversa, then you can just use directly it without a param and avoid check at all.
Take into account that the owner in this case will be a `ds-proxy`.

**Comment by maciejka** [comment]
Seems like a valid remark, in fact signatures of all methods that use isAllowed might be shortened. @kkostalkowicz any thoughts?

**Comment by gbalabasquer** [comment]
Btw, even using `msg.sender` you will need to extend the auth model like in the original manager.
For forking to or from `msg.sender`, the `manager` needs to be `hope`d in the `vat` by `msg.sender`. But if just does that, anyone with a vault will be able to access `msg.sender` funds in the `vat`, then something like [urnAllow](https://github.com/makerdao/dss-cdp-manager/blob/master/src/DssCdpManager.sol#L60) is needed

**Comment by gbalabasquer** [comment]
Part of this also applies to the other functions: `frob`, `flux` and `move`. Why do we need to pass `usr` if we always check is `msg.sender`?

**Comment by ghost** [comment]
> Seems like a valid remark, in fact signatures all methods that use isAllowed might be shortened.

True

BTW @gbalabasquer there's no point assigning issues to me, I'm no longer in the project

**Comment by gbalabasquer** [comment]
> > Seems like a valid remark, in fact signatures all methods that use isAllowed might be shortened.
> 
> True
> 
> BTW @gbalabasquer there's no point assigning issues to me, I'm no longer in the project

Ah ok, didn't know.

**Comment by gbalabasquer** [comment]
Done https://github.com/OasisDEX/oasis-cdp-manager/pull/5
